CREATE SEQUENCE seq_departments
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_courses
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_semesters
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_semesters_years
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_classes
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_events
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_repeat_events
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_repeat_days
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_assignments
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_grade_scales
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_assignment_categories
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_textbooks
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_syllabus_info
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_publishers
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_articles
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_authors
START WITH 1
INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_users
START WITH 1
INCREMENT BY 1 NOCACHE;
